// <auto-generated />
namespace OnlineBooking.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addbookingset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbookingset));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311453313_add-booking-set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
